#+TITLE: Sri Chinmoy Library repository
#+AUTHOR: 
#+OPTIONS: toc:nil 

* Sri Chinmoy Library repository

This repository contains the collected works of Sri Chinmoy.

It also includes the official bibliography of the works of Sri Chinmoy and related publications.

Each file contains the corresponding entry from the official bibliography.

The files follow the  =org-mode= syntax.

* Official site

This repository is hosted at:

https://bitbucket.org/vasudevaserver/sri-chinmoy-library-site

The repository is published at the [[http://www.srichinmoylibrary.com][Sri Chinmoy Library]]


* License

Sri Chinmoy wished to release all of his works under the following license:

/Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)/

In short, you are free to share, copy and redistribute the material in any medium or format under the following terms:

- *Attribution* — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
- *NonCommercial* — You may not use the material for commercial purposes.
- *NoDerivatives* — If you remix, transform, or build upon the material, you may not distribute the modified material.
- *No additional restrictions* — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits. 

The licensor cannot revoke these freedoms as long as you follow the license terms.

More information: [[https://creativecommons.org/licenses/by-nc-nd/4.0/][Creative Commons BY-NC-ND 4.0]]

