* The Archives of the works of Sri Chinmoy

This repository contains the published and unpublished works of [[http://www.srichinmoy.org][Sri Chinmoy]].

Currently the works have been grouped according to bibliographic type:

- book
- periodical
- songbook
- transcript

** Structure

Each work, published or unpublished, is a file contained in a folder.

Each file holds the corresponding entry from the official bibliography.

Series belongs to a common folder.

The files follow the [[http://orgmode.org/worg/dev/org-syntax.html][org]] syntax.

** Bibliography

The Archives include the official bibliography of the works of Sri Chinmoy, and related publications.


** Sites

The /Sri Chinmoy Archives/ are hosted at https://github.com/vscore/archives

The repository is published in different forms at different public sites.

One such site is the [[http://www.srichinmoylibrary.com][Sri Chinmoy Library]].

** Reporting issues

Any issue, like mistype, formatting, etc, can be reported by filing a ticket here:

https://github.com/vscore/file-issues/issues (free github account required)

That is a public issue-only repository.

Any issue regarding the /Sri Chinmoy Archives/, where published online as sites, or printed in books, are collected there.


** License

Sri Chinmoy's express wish was to release all of his works under the following license:

/Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)/

In short, you are free to share, copy and redistribute the material in any medium or format under the following terms:

- *Attribution* — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
- *NonCommercial* — You may not use the material for commercial purposes.
- *NoDerivatives* — If you remix, transform, or build upon the material, you may not distribute the modified material.
- *No additional restrictions* — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits. 

The licensor cannot revoke these freedoms as long as you follow the license terms.

More information: [[https://creativecommons.org/licenses/by-nc-nd/4.0/][Creative Commons BY-NC-ND 4.0]]

