** Spelling

Sri Chinmoy expressed the wish for the /Archives/ to favour spelling and grammar of British English as used at the turn of the 20th century, not the American spelling found in some of his editions. For now, the /Archives/ are following the /Oxford English Dictionary/ (but see note below), and also /A Dictionary of Modern English Usage/, by H.W. Fowler, specifically the first edition of 1926 (not any of the following editions).

In regard to the British English spelling, there is a subtle difference between the so-called "Oxford spelling" and "British English". We are supposed to use British English, not the former. In the following table, note for example how "realise" is spelt:



| British English             | Oxford spelling | American      |
| --------------------------- | --------------- | ------------- |
| analyse                     | analyse         | analyze       |
| behaviour                   | behaviour       | behavior      |
| centre                      | centre          | center        |
| defence                     | defence         | defense       |
| globalisation               | globalization   | globalization |
| realise                     | realize         | realize       |
| traveller                   | traveller       | traveler      |
| catalogue                   | catalogue       | catalog       |
| programme                   | programme       | program       |



** Headings / Titles

Following Sri Chinmoy's specific request to Vasudeva Server, the /Archives/ use sentence-style capitalisation in titles and headlines, where capitalisation follows the same rules that apply for sentences. This convention is sometimes called "sentence case": i.e. capitalisation of only the first word, proper nouns and as dictated by other specific British English rules.

Examples:

- The beauty of sound-life
- I came into the world to prove
- My Lord Beloved Supreme
- Spirituality and Christianity


NOTE: Sri Chinmoy's US first editions did follow US typography instead. Among US book publishers it is a common typographic practice to capitalise "important" words in titles and headings. Sri Chinmoy asked the Archives /not/ to follow that convention.

*** Notes

- If there are Titles which end with ellipses, it means that most probably they need to be completely changed. See the three examples below.

- If it is a question, then the title becomes the question, and that must be removed from the body of the chapter.

Before:

#+BEGIN_EXAMPLE
 * Question: How Can We Feel That The...
  :PROPERTIES:
  :GENRE: qa
  :END:

/Question:/ How can we feel that the inner world is more real than the outer world?

/Sri Chinmoy:/ The body, our outer sheath, is the outer world, and inside the body is the inner world.
#+END_EXAMPLE

After:

#+BEGIN_EXAMPLE
 * Question: How can we feel that the inner world is more real than the outer world?
  :PROPERTIES:
  :GENRE: qa
  :END:

/Sri Chinmoy:/ The body, our outer sheath, is the outer world, and inside the body is the inner world.
#+END_EXAMPLE


- If there is a poem, and the title is simply the first line of the verse, with ellipses, it means that a previous editor mistakenly assigned a wrong title. If there are no titles in the book, then numbers must be used.

Before:

#+BEGIN_EXAMPLE
 * 1 When I Go Out, ...
  :PROPERTIES:
  :GENRE: poem
  :END:

When I go out,
I am nowhere.
When I come in,
I am all-where.
#+END_EXAMPLE

After:

#+BEGIN_EXAMPLE
 * 1
  :PROPERTIES:
  :GENRE: poem
  :END:


When I go out,
I am nowhere.
When I come in,
I am all-where.

#+END_EXAMPLE


*** How to mark *** in centre of page.

#+BEGIN_EXAMPLE

#+BEGIN_CENTER
***
#+END_CENTER
#+END_EXAMPLE

Or, better, just use

={{{fleuron}}}=


*** Note

Sometimes poem titles do not have ellipses, but they just copy the first line of the verse. That could also be wrong, so each title must be checked with the original book.



** Fidelity to first edition content

Sri Chinmoy asked the /Archives/, independently from any other person or team working on his books, to carefully catalogue and archive his words only as they appeared in the very first edition, or as they were recorded in audio and video tapes or made into transcripts. Of course, not all works necessarily are to be published.

The /Archives/ main goal is to preserve Sri Chinmoy's original words, as they first appeared, in their pristine purity.

Sri Chinmoy asked the /Archives/ to catalogue, archive and publish (where proper) the very first run of the first edition of his books, even if some of that content might have changed later on. Where that is the case, Sri Chinmoy asked /Archives/ to note later changes, but to preserve the original version on the main page.


** Use of personal names

One of the few exceptions to fidelity to the first edition guideline regards the use of names.

1. If a name belongs to a non-disciple, (for example, interviewer, VIP, etc), it should be left as is, no matter where it appears.

2. If a disciple's name appears in an editorial section, it should be substituted with its initial.

3. If a disciple's name appears in the body of Sri Chinmoy's writings, that name should be kept as is, even if the disciple has passed on, or perhaps is not currently following Sri Chinmoy's path.

4. Some particular names appearing in the body of Sri Chinmoy's writings should be written as an initial (like case 2). In case of uncertainty it is better to ask.

5. Where used, initials do not carry a period. Use: "Question asked by N in New York." Not, "Question asked by N. in New York."



** Typography

When asked about which typographic rules to follow, Sri Chinmoy expressed the wish to have his books (at least the ones catalogued, preserved and published by Vasudeva Server) to follow the British-French rules, as they were used in the Ashram.

He specifically asked the /Archives/ not to use American rules. An example he offered regards the use of "guillemets" (or angle quotes), as they should be preferred to American or English typographic quotation marks where proper.

"British-French" rules at the turn of the 20th century are not easy to identify, and unfortunately we do not have many other examples like that. 

The right mix between British and French is not easy to get. Unfortunately, the Ashram books available now are following either American or purely British rules, so they cannot be used as examples. Necessarily some things will need to be decided on the way.



  
*** Italics and punctuation

The use of punctuation within or without italics is subject to quite a few opinions, sometimes opposite.

This is a matter belonging more to style guides of different publications than grammar. Style guides of major British publishing houses differ on this matter.

It is correct to assume that one can put punctuation marks in italics when the punctuation marks follow straight after the part which has been put in italics.

Since the use of italics already expresses a strong semantic connotation which prevents misunderstanding, we tend to follow the typographic convention of always including punctuation within italics, for sake of aesthetics. There may be a few exceptions, though.

Use:

#+BEGIN_EXAMPLE
The Editor of /Hinduism Today,/
#+END_EXAMPLE

and not 

#+BEGIN_EXAMPLE
The Editor of /Hinduism Today/,
#+END_EXAMPLE


